language: python
python:
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# main script for now
script:
  - "python gru_classification.py travis"